# Generated by Django 3.0.2 on 2020-03-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppify', '0006_auto_20200320_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('idform', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idquestion', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('idreponse', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
                ('idpersonne', models.OneToOneField(db_column='idpersonne', on_delete=django.db.models.deletion.DO_NOTHING, to='puppify.Utilisateur')),
                ('idquestion', models.ForeignKey(db_column='idquestion', on_delete=django.db.models.deletion.DO_NOTHING, to='puppify.Question')),
            ],
            options={
                'unique_together': {('idpersonne', 'idquestion')},
            },
        ),
        migrations.CreateModel(
            name='QuestionForm',
            fields=[
                ('idquestionform', models.AutoField(primary_key=True, serialize=False)),
                ('idformulaire', models.OneToOneField(db_column='idformulaire', on_delete=django.db.models.deletion.DO_NOTHING, to='puppify.Formulaire')),
                ('idquestion', models.OneToOneField(db_column='idquestion', on_delete=django.db.models.deletion.DO_NOTHING, to='puppify.Question')),
            ],
            options={
                'unique_together': {('idquestion', 'idformulaire')},
            },
        ),
    ]
